### ISSUE TITLE
Question about results reported in Experiment 4.2 in the paper

### ISSUE THREAD

**Issue by riverback** [visinf/fast-axiomatic-attribution#1]
Thank you for your wonderful work, but I'm a little confused about the results reported in Experiment 4.2 in the paper.

According to the metrics proposed by Lundberg et al., these metrics (KPM, KNM, KAM, RAM) should be from 0 to 1 (or from -1 to 1), but the results in Table 3 are much larger than 1

Would you please give an explanation to help me reproduce the results? Thank you very much!

Lundberg, S.M., Erion, G., Chen, H. et al. From local explanations to global understanding with explainable AI for trees. Nat Mach Intell 2, 56–67 (2020). https://doi.org/10.1038/s42256-019-0138-9

**Comment by robinhesse** [comment]
Hi,

thank you very much for your interest in our work! I assume this difference is due to using Softmax normalization (0-1 range) or not.

Best,
Robin
